* Experiment - RPG Events

** Purpose

Create a simple map that you can walk around. Have some small
interactive objects and a script cut-scene.


** Info

Nothing too special, just a character walking around a map like in
most RPG's. Game objects are built using the [[http://sodaware.github.com/apollo/][apollo]] entity framework.


** Development Notes

*** Components

Smaller components are better than big, monolithic ones. A lot of functionality
can be shared by splitting a component. For example, in this demo the player was
originally a PlayerComponent which contained a Flixel sprite. However, NPC's and
other objects also need to sprite, so this should be moved


** Requirements

*** DONE Tilemap
*** DONE Moveable Character
*** TODO Chest you can open
*** TODO NPC you can talk to [0/2]
    - [ ] Says a line of text
    - [ ] Says something different if you have item from chest
*** TODO Cutscene [0/5]
    - [ ] Pushing a lever triggers the scene
    - [ ] Someone walks by
    - [ ] Says something
    - [ ] Walks off
    - [ ] Play resumes
